// languages.js
export const languages = [
    { name: 'Markup - HTML, XML, etc.', value: 'markup' },
    { name: 'CSS', value: 'css' },
    { name: 'C-like', value: 'clike' },
    { name: 'JavaScript', value: 'javascript' },
    { name: 'ABAP', value: 'abap' },
    { name: 'ABNF', value: 'abnf' },
    { name: 'ActionScript', value: 'actionscript' },
    { name: 'Ada', value: 'ada' },
    { name: 'Agda', value: 'agda' },
    { name: 'AL', value: 'al' },
    { name: 'ANTLR4', value: 'antlr4' },
    { name: 'Apache Configuration', value: 'apacheconf' },
    { name: 'Apex', value: 'apex' },
    { name: 'APL', value: 'apl' },
    { name: 'AppleScript', value: 'applescript' },
    { name: 'AQL', value: 'aql' },
    { name: 'Arduino', value: 'arduino' },
    { name: 'ARFF', value: 'arff' },
    { name: 'ARM Assembly', value: 'armasm' },
    { name: 'Arturo', value: 'arturo' },
    { name: 'AsciiDoc', value: 'asciidoc' },
    { name: 'ASP.NET (C#)', value: 'aspnet' },
    { name: '6502 Assembly', value: 'asm6502' },
    { name: 'Atmel AVR Assembly', value: 'asmatmel' },
    { name: 'AutoHotkey', value: 'autohotkey' },
    { name: 'AutoIt', value: 'autoit' },
    { name: 'AviSynth', value: 'avisynth' },
    { name: 'Avro IDL', value: 'avro-idl' },
    { name: 'AWK', value: 'awk' },
    { name: 'Bash', value: 'bash' },
    { name: 'BASIC', value: 'basic' },
    { name: 'Batch', value: 'batch' },
    { name: 'BBcode', value: 'bbcode' },
    { name: 'BBj', value: 'bbj' },
    { name: 'Bicep', value: 'bicep' },
    { name: 'Birb', value: 'birb' },
    { name: 'Bison', value: 'bison' },
    { name: 'BNF', value: 'bnf' },
    { name: 'BQN', value: 'bqn' },
    { name: 'Brainfuck', value: 'brainfuck' },
    { name: 'BrightScript', value: 'brightscript' },
    { name: 'Bro', value: 'bro' },
    { name: 'BSL (1C:Enterprise)', value: 'bsl' },
    { name: 'C', value: 'c' },
    { name: 'C#', value: 'csharp' },
    { name: 'C++', value: 'cpp' },
    { name: 'CFScript', value: 'cfscript' },
    { name: 'ChaiScript', value: 'chaiscript' },
    { name: 'CIL', value: 'cil' },
    { name: 'Cilk/C', value: 'cilkc' },
    { name: 'Cilk/C++', value: 'cilkcpp' },
    { name: 'Clojure', value: 'clojure' },
    { name: 'CMake', value: 'cmake' },
    { name: 'COBOL', value: 'cobol' },
    { name: 'CoffeeScript', value: 'coffeescript' },
    { name: 'Concurnas', value: 'concurnas' },
    { name: 'Content-Security-Policy', value: 'csp' },
    { name: 'Cooklang', value: 'cooklang' },
    { name: 'Coq', value: 'coq' },
    { name: 'Crystal', value: 'crystal' },
    { name: 'CSS Extras', value: 'css-extras' },
    { name: 'CSV', value: 'csv' },
    { name: 'CUE', value: 'cue' },
    { name: 'Cypher', value: 'cypher' },
    { name: 'D', value: 'd' },
    { name: 'Dart', value: 'dart' },
    { name: 'DataWeave', value: 'dataweave' },
    { name: 'DAX', value: 'dax' },
    { name: 'Dhall', value: 'dhall' },
    { name: 'Diff', value: 'diff' },
    { name: 'Django/Jinja2', value: 'django' },
    { name: 'DNS zone file', value: 'dns-zone-file' },
    { name: 'Docker', value: 'docker' },
    { name: 'DOT (Graphviz)', value: 'dot' },
    { name: 'EBNF', value: 'ebnf' },
    { name: 'EditorConfig', value: 'editorconfig' },
    { name: 'Eiffel', value: 'eiffel' },
    { name: 'EJS', value: 'ejs' },
    { name: 'Elixir', value: 'elixir' },
    { name: 'Elm', value: 'elm' },
    { name: 'Embedded Lua templating', value: 'etlua' },
    { name: 'ERB', value: 'erb' },
    { name: 'Erlang', value: 'erlang' },
    { name: 'Excel Formula', value: 'excel-formula' },
    { name: 'F#', value: 'fsharp' },
    { name: 'Factor', value: 'factor' },
    { name: 'False', value: 'false' },
    { name: 'Firestore security rules', value: 'firestore-security-rules' },
    { name: 'Flow', value: 'flow' },
    { name: 'Fortran', value: 'fortran' },
    { name: 'FreeMarker Template Language', value: 'ftl' },
    { name: 'GameMaker Language', value: 'gml' },
    { name: 'GAP (CAS)', value: 'gap' },
    { name: 'G-code', value: 'gcode' },
    { name: 'GDScript', value: 'gdscript' },
    { name: 'GEDCOM', value: 'gedcom' },
    { name: 'gettext', value: 'gettext' },
    { name: 'Gherkin', value: 'gherkin' },
    { name: 'Git', value: 'git' },
    { name: 'GLSL', value: 'glsl' },
    { name: 'GN', value: 'gn' },
    { name: 'GNU Linker Script', value: 'linker-script' },
    { name: 'Go', value: 'go' },
    { name: 'Go module', value: 'go-module' },
    { name: 'Gradle', value: 'gradle' },
    { name: 'GraphQL', value: 'graphql' },
    { name: 'Groovy', value: 'groovy' },
    { name: 'Haml', value: 'haml' },
    { name: 'Handlebars', value: 'handlebars' },
    { name: 'Haskell', value: 'haskell' },
    { name: 'Haxe', value: 'haxe' },
    { name: 'HCL', value: 'hcl' },
    { name: 'HLSL', value: 'hlsl' },
    { name: 'Hoon', value: 'hoon' },
    { name: 'HTTP', value: 'http' },
    { name: 'HTTP Public-Key-Pins', value: 'hpkp' },
    { name: 'HTTP Strict-Transport-Security', value: 'hsts' },
    { name: 'IchigoJam', value: 'ichigojam' },
    { name: 'Icon', value: 'icon' },
    { name: 'ICU Message Format', value: 'icu-message-format' },
    { name: 'Idris', value: 'idris' },
    { name: '.ignore', value: 'ignore' },
    { name: 'Inform 7', value: 'inform7' },
    { name: 'Ini', value: 'ini' },
    { name: 'Io', value: 'io' },
    { name: 'J', value: 'j' },
    { name: 'Java', value: 'java' },
    { name: 'JavaDoc', value: 'javadoc' },
    { name: 'JavaDoc-like', value: 'javadoclike' },
    { name: 'Java stack trace', value: 'javastacktrace' },
    { name: 'Jexl', value: 'jexl' },
    { name: 'Jolie', value: 'jolie' },
    { name: 'JQ', value: 'jq' },
    { name: 'JSDoc', value: 'jsdoc' },
    { name: 'JS Extras', value: 'js-extras' },
    { name: 'JSON', value: 'json' },
    { name: 'JSON5', value: 'json5' },
    { name: 'JSONP', value: 'jsonp' },
    { name: 'JS stack trace', value: 'jsstacktrace' },
    { name: 'JS Templates', value: 'js-templates' },
    { name: 'Julia', value: 'julia' },
    { name: 'Keepalived Configure', value: 'keepalived' },
    { name: 'Keyman', value: 'keyman' },
    { name: 'Kotlin', value: 'kotlin' },
    { name: 'KuMir (КуМир)', value: 'kumir' },
    { name: 'Kusto', value: 'kusto' },
    { name: 'LaTeX', value: 'latex' },
    { name: 'Latte', value: 'latte' },
    { name: 'Less', value: 'less' },
    { name: 'LilyPond', value: 'lilypond' },
    { name: 'Liquid', value: 'liquid' },
    { name: 'Lisp', value: 'lisp' },
    { name: 'LiveScript', value: 'livescript' },
    { name: 'LLVM IR', value: 'llvm' },
    { name: 'Log file', value: 'log' },
    { name: 'LOLCODE', value: 'lolcode' },
    { name: 'Lua', value: 'lua' },
    { name: 'Magma (CAS)', value: 'magma' },
    { name: 'Makefile', value: 'makefile' },
    { name: 'Markdown', value: 'markdown' },
    { name: 'Markup templating', value: 'markup-templating' },
    { name: 'Mata', value: 'mata' },
    { name: 'MATLAB', value: 'matlab' },
    { name: 'MAXScript', value: 'maxscript' },
    { name: 'MEL', value: 'mel' },
    { name: 'Mermaid', value: 'mermaid' },
    { name: 'METAFONT', value: 'metafont' },
    { name: 'Mizar', value: 'mizar' },
    { name: 'MongoDB', value: 'mongodb' },
    { name: 'Monkey', value: 'monkey' },
    { name: 'MoonScript', value: 'moonscript' },
    { name: 'N1QL', value: 'n1ql' },
    { name: 'N4JS', value: 'n4js' },
    { name: 'Nand To Tetris HDL', value: 'nand2tetris-hdl' },
    { name: 'Naninovel Script', value: 'naniscript' },
    { name: 'NASM', value: 'nasm' },
    { name: 'NEON', value: 'neon' },
    { name: 'Nevod', value: 'nevod' },
    { name: 'nginx', value: 'nginx' },
    { name: 'Nim', value: 'nim' },
    { name: 'Nix', value: 'nix' },
    { name: 'NSIS', value: 'nsis' },
    { name: 'Objective-C', value: 'objectivec' },
    { name: 'OCaml', value: 'ocaml' },
    { name: 'Odin', value: 'odin' },
    { name: 'OpenCL', value: 'opencl' },
    { name: 'OpenQasm', value: 'openqasm' },
    { name: 'Oz', value: 'oz' },
    { name: 'PARI/GP', value: 'parigp' },
    { name: 'Parser', value: 'parser' },
    { name: 'Pascal', value: 'pascal' },
    { name: 'Pascaligo', value: 'pascaligo' },
    { name: 'PATROL Scripting Language', value: 'psl' },
    { name: 'PC-Axis', value: 'pcaxis' },
    { name: 'PeopleCode', value: 'peoplecode' },
    { name: 'Perl', value: 'perl' },
    { name: 'PHP', value: 'php' },
    { name: 'PHPDoc', value: 'phpdoc' },
    { name: 'PHP Extras', value: 'php-extras' },
    { name: 'PlantUML', value: 'plant-uml' },
    { name: 'PL/SQL', value: 'plsql' },
    { name: 'PowerQuery', value: 'powerquery' },
    { name: 'PowerShell', value: 'powershell' },
    { name: 'Processing', value: 'processing' },
    { name: 'Prolog', value: 'prolog' },
    { name: 'PromQL', value: 'promql' },
    { name: '.properties', value: 'properties' },
    { name: 'Protocol Buffers', value: 'protobuf' },
    { name: 'Pug', value: 'pug' },
    { name: 'Puppet', value: 'puppet' },
    { name: 'Pure', value: 'pure' },
    { name: 'PureBasic', value: 'purebasic' },
    { name: 'PureScript', value: 'purescript' },
    { name: 'Python', value: 'python' },
    { name: 'Q#', value: 'qsharp' },
    { name: 'Q (kdb+ database)', value: 'q' },
    { name: 'QML', value: 'qml' },
    { name: 'Qore', value: 'qore' },
    { name: 'R', value: 'r' },
    { name: 'Racket', value: 'racket' },
    { name: 'Razor C#', value: 'cshtml' },
    { name: 'React JSX', value: 'jsx' },
    { name: 'React TSX', value: 'tsx' },
    { name: 'Reason', value: 'reason' },
    { name: 'Regex', value: 'regex' },
    { name: 'Rego', value: 'rego' },
    { name: "Ren'py", value: 'renpy' },
    { name: 'ReScript', value: 'rescript' },
    { name: 'reST (reStructuredText)', value: 'rest' },
    { name: 'Rip', value: 'rip' },
    { name: 'Roboconf', value: 'roboconf' },
    { name: 'Robot Framework', value: 'robotframework' },
    { name: 'Ruby', value: 'ruby' },
    { name: 'Rust', value: 'rust' },
    { name: 'SAS', value: 'sas' },
    { name: 'Sass (Sass)', value: 'sass' },
    { name: 'Sass (SCSS)', value: 'scss' },
    { name: 'Scala', value: 'scala' },
    { name: 'Scheme', value: 'scheme' },
    { name: 'Shell session', value: 'shell-session' },
    { name: 'Smali', value: 'smali' },
    { name: 'Smalltalk', value: 'smalltalk' },
    { name: 'Smarty', value: 'smarty' },
    { name: 'SML', value: 'sml' },
    { name: 'Solidity (Ethereum)', value: 'solidity' },
    { name: 'Solution file', value: 'solution-file' },
    { name: 'Soy (Closure Template)', value: 'soy' },
    { name: 'SPARQL', value: 'sparql' },
    { name: 'Splunk SPL', value: 'splunk-spl' },
    { name: 'SQF: Status Quo Function (Arma 3)', value: 'sqf' },
    { name: 'SQL', value: 'sql' },
    { name: 'Squirrel', value: 'squirrel' },
    { name: 'Stan', value: 'stan' },
    { name: 'Stata Ado', value: 'stata' },
    { name: 'Structured Text (IEC 61131-3)', value: 'iecst' },
    { name: 'Stylus', value: 'stylus' },
    { name: 'SuperCollider', value: 'supercollider' },
    { name: 'Swift', value: 'swift' },
    { name: 'Systemd configuration file', value: 'systemd' },
    { name: 'T4 templating', value: 't4-templating' },
    { name: 'T4 Text Templates (C#)', value: 't4-cs' },
    { name: 'T4 Text Templates (VB)', value: 't4-vb' },
    { name: 'TAP', value: 'tap' },
    { name: 'Tcl', value: 'tcl' },
    { name: 'Template Toolkit 2', value: 'tt2' },
    { name: 'Textile', value: 'textile' },
    { name: 'TOML', value: 'toml' },
    { name: 'Tremor', value: 'tremor' },
    { name: 'Turtle', value: 'turtle' },
    { name: 'Twig', value: 'twig' },
    { name: 'TypeScript', value: 'typescript' },
    { name: 'TypoScript', value: 'typoscript' },
    { name: 'UnrealScript', value: 'unrealscript' },
    { name: 'UO Razor Script', value: 'uorazor' },
    { name: 'URI', value: 'uri' },
    { name: 'V', value: 'v' },
    { name: 'Vala', value: 'vala' },
    { name: 'VB.Net', value: 'vbnet' },
    { name: 'Velocity', value: 'velocity' },
    { name: 'Verilog', value: 'verilog' },
    { name: 'VHDL', value: 'vhdl' },
    { name: 'vim', value: 'vim' },
    { name: 'Visual Basic', value: 'visual-basic' },
    { name: 'WarpScript', value: 'warpscript' },
    { name: 'WebAssembly', value: 'wasm' },
    { name: 'Web IDL', value: 'web-idl' },
    { name: 'WGSL', value: 'wgsl' },
    { name: 'Wiki markup', value: 'wiki' },
    { name: 'Wolfram language', value: 'wolfram' },
    { name: 'Wren', value: 'wren' },
    { name: 'Xeora', value: 'xeora' },
    { name: 'XML doc (.net)', value: 'xml-doc' },
    { name: 'Xojo (REALbasic)', value: 'xojo' },
    { name: 'XQuery', value: 'xquery' },
    { name: 'YAML', value: 'yaml' },
    { name: 'YANG', value: 'yang' },
    { name: 'Zig', value: 'zig' },
  ];
  